/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeightLossPeptidesRouteImport } from './routes/weight-loss-peptides'
import { Route as TissueRepairPeptidesRouteImport } from './routes/tissue-repair-peptides'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as SenolyticLongevityPeptidesRouteImport } from './routes/senolytic-longevity-peptides'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ReturnsPolicyRouteImport } from './routes/returns-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RecoveryPeptidesRouteImport } from './routes/recovery-peptides'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PressRouteImport } from './routes/press'
import { Route as NootropicsRouteImport } from './routes/nootropics'
import { Route as LongevityPeptidesRouteImport } from './routes/longevity-peptides'
import { Route as GrowthHormoneSecretagoguesRouteImport } from './routes/growth-hormone-secretagogues'
import { Route as GrowthHormonePeptidesRouteImport } from './routes/growth-hormone-peptides'
import { Route as Glp1MetabolicPeptidesRouteImport } from './routes/glp1-metabolic-peptides'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CognitiveNeuropeptidesRouteImport } from './routes/cognitive-neuropeptides'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BundlesIndexRouteImport } from './routes/bundles.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as BundlesSlugRouteImport } from './routes/bundles.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const WeightLossPeptidesRoute = WeightLossPeptidesRouteImport.update({
  id: '/weight-loss-peptides',
  path: '/weight-loss-peptides',
  getParentRoute: () => rootRouteImport,
} as any)
const TissueRepairPeptidesRoute = TissueRepairPeptidesRouteImport.update({
  id: '/tissue-repair-peptides',
  path: '/tissue-repair-peptides',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SenolyticLongevityPeptidesRoute =
  SenolyticLongevityPeptidesRouteImport.update({
    id: '/senolytic-longevity-peptides',
    path: '/senolytic-longevity-peptides',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsPolicyRoute = ReturnsPolicyRouteImport.update({
  id: '/returns-policy',
  path: '/returns-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryPeptidesRoute = RecoveryPeptidesRouteImport.update({
  id: '/recovery-peptides',
  path: '/recovery-peptides',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const NootropicsRoute = NootropicsRouteImport.update({
  id: '/nootropics',
  path: '/nootropics',
  getParentRoute: () => rootRouteImport,
} as any)
const LongevityPeptidesRoute = LongevityPeptidesRouteImport.update({
  id: '/longevity-peptides',
  path: '/longevity-peptides',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthHormoneSecretagoguesRoute =
  GrowthHormoneSecretagoguesRouteImport.update({
    id: '/growth-hormone-secretagogues',
    path: '/growth-hormone-secretagogues',
    getParentRoute: () => rootRouteImport,
  } as any)
const GrowthHormonePeptidesRoute = GrowthHormonePeptidesRouteImport.update({
  id: '/growth-hormone-peptides',
  path: '/growth-hormone-peptides',
  getParentRoute: () => rootRouteImport,
} as any)
const Glp1MetabolicPeptidesRoute = Glp1MetabolicPeptidesRouteImport.update({
  id: '/glp1-metabolic-peptides',
  path: '/glp1-metabolic-peptides',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitiveNeuropeptidesRoute = CognitiveNeuropeptidesRouteImport.update({
  id: '/cognitive-neuropeptides',
  path: '/cognitive-neuropeptides',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesIndexRoute = BundlesIndexRouteImport.update({
  id: '/bundles/',
  path: '/bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesSlugRoute = BundlesSlugRouteImport.update({
  id: '/bundles/$slug',
  path: '/bundles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cognitive-neuropeptides': typeof CognitiveNeuropeptidesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faqs': typeof FaqsRoute
  '/glp1-metabolic-peptides': typeof Glp1MetabolicPeptidesRoute
  '/growth-hormone-peptides': typeof GrowthHormonePeptidesRoute
  '/growth-hormone-secretagogues': typeof GrowthHormoneSecretagoguesRoute
  '/longevity-peptides': typeof LongevityPeptidesRoute
  '/nootropics': typeof NootropicsRoute
  '/press': typeof PressRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recovery-peptides': typeof RecoveryPeptidesRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/senolytic-longevity-peptides': typeof SenolyticLongevityPeptidesRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/tissue-repair-peptides': typeof TissueRepairPeptidesRoute
  '/weight-loss-peptides': typeof WeightLossPeptidesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bundles/$slug': typeof BundlesSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/blog/': typeof BlogIndexRoute
  '/bundles/': typeof BundlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cognitive-neuropeptides': typeof CognitiveNeuropeptidesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faqs': typeof FaqsRoute
  '/glp1-metabolic-peptides': typeof Glp1MetabolicPeptidesRoute
  '/growth-hormone-peptides': typeof GrowthHormonePeptidesRoute
  '/growth-hormone-secretagogues': typeof GrowthHormoneSecretagoguesRoute
  '/longevity-peptides': typeof LongevityPeptidesRoute
  '/nootropics': typeof NootropicsRoute
  '/press': typeof PressRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recovery-peptides': typeof RecoveryPeptidesRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/senolytic-longevity-peptides': typeof SenolyticLongevityPeptidesRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/tissue-repair-peptides': typeof TissueRepairPeptidesRoute
  '/weight-loss-peptides': typeof WeightLossPeptidesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bundles/$slug': typeof BundlesSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/blog': typeof BlogIndexRoute
  '/bundles': typeof BundlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cognitive-neuropeptides': typeof CognitiveNeuropeptidesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faqs': typeof FaqsRoute
  '/glp1-metabolic-peptides': typeof Glp1MetabolicPeptidesRoute
  '/growth-hormone-peptides': typeof GrowthHormonePeptidesRoute
  '/growth-hormone-secretagogues': typeof GrowthHormoneSecretagoguesRoute
  '/longevity-peptides': typeof LongevityPeptidesRoute
  '/nootropics': typeof NootropicsRoute
  '/press': typeof PressRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recovery-peptides': typeof RecoveryPeptidesRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/senolytic-longevity-peptides': typeof SenolyticLongevityPeptidesRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/tissue-repair-peptides': typeof TissueRepairPeptidesRoute
  '/weight-loss-peptides': typeof WeightLossPeptidesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bundles/$slug': typeof BundlesSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/blog/': typeof BlogIndexRoute
  '/bundles/': typeof BundlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cancellation-policy'
    | '/cognitive-neuropeptides'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faqs'
    | '/glp1-metabolic-peptides'
    | '/growth-hormone-peptides'
    | '/growth-hormone-secretagogues'
    | '/longevity-peptides'
    | '/nootropics'
    | '/press'
    | '/privacy-policy'
    | '/recovery-peptides'
    | '/refund-policy'
    | '/returns-policy'
    | '/reviews'
    | '/senolytic-longevity-peptides'
    | '/shipping-policy'
    | '/shop'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/tissue-repair-peptides'
    | '/weight-loss-peptides'
    | '/blog/$slug'
    | '/bundles/$slug'
    | '/product/$handle'
    | '/blog/'
    | '/bundles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cancellation-policy'
    | '/cognitive-neuropeptides'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faqs'
    | '/glp1-metabolic-peptides'
    | '/growth-hormone-peptides'
    | '/growth-hormone-secretagogues'
    | '/longevity-peptides'
    | '/nootropics'
    | '/press'
    | '/privacy-policy'
    | '/recovery-peptides'
    | '/refund-policy'
    | '/returns-policy'
    | '/reviews'
    | '/senolytic-longevity-peptides'
    | '/shipping-policy'
    | '/shop'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/tissue-repair-peptides'
    | '/weight-loss-peptides'
    | '/blog/$slug'
    | '/bundles/$slug'
    | '/product/$handle'
    | '/blog'
    | '/bundles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cancellation-policy'
    | '/cognitive-neuropeptides'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/faqs'
    | '/glp1-metabolic-peptides'
    | '/growth-hormone-peptides'
    | '/growth-hormone-secretagogues'
    | '/longevity-peptides'
    | '/nootropics'
    | '/press'
    | '/privacy-policy'
    | '/recovery-peptides'
    | '/refund-policy'
    | '/returns-policy'
    | '/reviews'
    | '/senolytic-longevity-peptides'
    | '/shipping-policy'
    | '/shop'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/tissue-repair-peptides'
    | '/weight-loss-peptides'
    | '/blog/$slug'
    | '/bundles/$slug'
    | '/product/$handle'
    | '/blog/'
    | '/bundles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  CognitiveNeuropeptidesRoute: typeof CognitiveNeuropeptidesRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqsRoute: typeof FaqsRoute
  Glp1MetabolicPeptidesRoute: typeof Glp1MetabolicPeptidesRoute
  GrowthHormonePeptidesRoute: typeof GrowthHormonePeptidesRoute
  GrowthHormoneSecretagoguesRoute: typeof GrowthHormoneSecretagoguesRoute
  LongevityPeptidesRoute: typeof LongevityPeptidesRoute
  NootropicsRoute: typeof NootropicsRoute
  PressRoute: typeof PressRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RecoveryPeptidesRoute: typeof RecoveryPeptidesRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ReturnsPolicyRoute: typeof ReturnsPolicyRoute
  ReviewsRoute: typeof ReviewsRoute
  SenolyticLongevityPeptidesRoute: typeof SenolyticLongevityPeptidesRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  ShopRoute: typeof ShopRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ThankYouRoute: typeof ThankYouRoute
  TissueRepairPeptidesRoute: typeof TissueRepairPeptidesRoute
  WeightLossPeptidesRoute: typeof WeightLossPeptidesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BundlesSlugRoute: typeof BundlesSlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BundlesIndexRoute: typeof BundlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weight-loss-peptides': {
      id: '/weight-loss-peptides'
      path: '/weight-loss-peptides'
      fullPath: '/weight-loss-peptides'
      preLoaderRoute: typeof WeightLossPeptidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tissue-repair-peptides': {
      id: '/tissue-repair-peptides'
      path: '/tissue-repair-peptides'
      fullPath: '/tissue-repair-peptides'
      preLoaderRoute: typeof TissueRepairPeptidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senolytic-longevity-peptides': {
      id: '/senolytic-longevity-peptides'
      path: '/senolytic-longevity-peptides'
      fullPath: '/senolytic-longevity-peptides'
      preLoaderRoute: typeof SenolyticLongevityPeptidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-policy': {
      id: '/returns-policy'
      path: '/returns-policy'
      fullPath: '/returns-policy'
      preLoaderRoute: typeof ReturnsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-peptides': {
      id: '/recovery-peptides'
      path: '/recovery-peptides'
      fullPath: '/recovery-peptides'
      preLoaderRoute: typeof RecoveryPeptidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nootropics': {
      id: '/nootropics'
      path: '/nootropics'
      fullPath: '/nootropics'
      preLoaderRoute: typeof NootropicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/longevity-peptides': {
      id: '/longevity-peptides'
      path: '/longevity-peptides'
      fullPath: '/longevity-peptides'
      preLoaderRoute: typeof LongevityPeptidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-hormone-secretagogues': {
      id: '/growth-hormone-secretagogues'
      path: '/growth-hormone-secretagogues'
      fullPath: '/growth-hormone-secretagogues'
      preLoaderRoute: typeof GrowthHormoneSecretagoguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-hormone-peptides': {
      id: '/growth-hormone-peptides'
      path: '/growth-hormone-peptides'
      fullPath: '/growth-hormone-peptides'
      preLoaderRoute: typeof GrowthHormonePeptidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glp1-metabolic-peptides': {
      id: '/glp1-metabolic-peptides'
      path: '/glp1-metabolic-peptides'
      fullPath: '/glp1-metabolic-peptides'
      preLoaderRoute: typeof Glp1MetabolicPeptidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive-neuropeptides': {
      id: '/cognitive-neuropeptides'
      path: '/cognitive-neuropeptides'
      fullPath: '/cognitive-neuropeptides'
      preLoaderRoute: typeof CognitiveNeuropeptidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/': {
      id: '/bundles/'
      path: '/bundles'
      fullPath: '/bundles/'
      preLoaderRoute: typeof BundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$slug': {
      id: '/bundles/$slug'
      path: '/bundles/$slug'
      fullPath: '/bundles/$slug'
      preLoaderRoute: typeof BundlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  CognitiveNeuropeptidesRoute: CognitiveNeuropeptidesRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqsRoute: FaqsRoute,
  Glp1MetabolicPeptidesRoute: Glp1MetabolicPeptidesRoute,
  GrowthHormonePeptidesRoute: GrowthHormonePeptidesRoute,
  GrowthHormoneSecretagoguesRoute: GrowthHormoneSecretagoguesRoute,
  LongevityPeptidesRoute: LongevityPeptidesRoute,
  NootropicsRoute: NootropicsRoute,
  PressRoute: PressRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RecoveryPeptidesRoute: RecoveryPeptidesRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ReturnsPolicyRoute: ReturnsPolicyRoute,
  ReviewsRoute: ReviewsRoute,
  SenolyticLongevityPeptidesRoute: SenolyticLongevityPeptidesRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  ShopRoute: ShopRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ThankYouRoute: ThankYouRoute,
  TissueRepairPeptidesRoute: TissueRepairPeptidesRoute,
  WeightLossPeptidesRoute: WeightLossPeptidesRoute,
  BlogSlugRoute: BlogSlugRoute,
  BundlesSlugRoute: BundlesSlugRoute,
  ProductHandleRoute: ProductHandleRoute,
  BlogIndexRoute: BlogIndexRoute,
  BundlesIndexRoute: BundlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
